### PR TITLE
Fix function and package comments

### PR DESCRIPTION
**Pull request by alexandear**
This PR updates comments for functions and packages to ensure that the names in comments and code are synchronized. See https://go.dev/doc/comment.

Additionally, it enables `EXC0013` and `EXC0014` to prevent these issues from recurring. `revive` will now flag any discrepancies. Comments on exported constants are ignored.

<details>
<summary>The full list of comment issues that were fixed</summary>

```
❯ golangci-lint run
pkg/start/start.go:327:1: exported: comment on exported function WithWatchHostAgentTimeout should be of the form "WithWatchHostAgentTimeout ..." (revive)
// WithWatchHostAgentEventsTimeout sets the value of the timeout to use for
^
pkg/guestagent/kubernetesservice/kubernetesservice.go:25:2: exported: comment on exported const TCP should be of the form "TCP ..." (revive)
        // UDP/SCTP when lima port forwarding works on those protocols.
        ^
pkg/guestagent/api/gen.go:1:1: package-comments: package comment should be of the form "Package api ..." (revive)
//go:generate protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative guestservice.proto --descriptor_set_out=guestservice.pb.desc
^
pkg/store/filenames/filenames.go:11:28: exported: comment on exported const CacheDir should be of the form "CacheDir ..." (revive)
        CacheDir    = "_cache"    // not yet implemented
                                  ^
pkg/store/filenames/filenames.go:12:28: exported: comment on exported const NetworksDir should be of the form "NetworksDir ..." (revive)
        NetworksDir = "_networks" // network log files are stored here
                                  ^
pkg/store/filenames/filenames.go:13:28: exported: comment on exported const DisksDir should be of the form "DisksDir ..." (revive)
        DisksDir    = "_disks"    // disks are stored here
                                  ^
pkg/store/filenames/filenames.go:30:40: exported: comment on exported const LimaVersion should be of the form "LimaVersion ..." (revive)
        LimaVersion          = "lima-version" // Lima version used to create instance
                                              ^
pkg/store/filenames/filenames.go:39:38: exported: comment on exported const SerialLog should be of the form "SerialLog ..." (revive)
        SerialLog            = "serial.log" // default serial (ttyS0, but ttyAMA0 on qemu-system-{arm,aarch64})
                                            ^
pkg/store/filenames/filenames.go:41:39: exported: comment on exported const SerialPCILog should be of the form "SerialPCILog ..." (revive)
        SerialPCILog         = "serialp.log" // pci serial (ttyS0 on qemu-system-{arm,aarch64})
                                             ^
pkg/store/filenames/filenames.go:43:39: exported: comment on exported const SerialVirtioLog should be of the form "SerialVirtioLog ..." (revive)
        SerialVirtioLog      = "serialv.log" // virtio serial
                                             ^
pkg/store/filenames/filenames.go:57:44: exported: comment on exported const VzEfi should be of the form "VzEfi ..." (revive)
        VzEfi                = "vz-efi"           // efi variable store
                                                  ^
pkg/store/filenames/filenames.go:58:44: exported: comment on exported const QemuEfiCodeFD should be of the form "QemuEfiCodeFD ..." (revive)
        QemuEfiCodeFD        = "qemu-efi-code.fd" // efi code; not always created
                                                  ^
pkg/store/filenames/filenames.go:64:26: exported: comment on exported const Protected should be of the form "Protected ..." (revive)
        Protected = "protected" // empty file; used by `limactl protect`
                                ^
pkg/networks/const.go:5:2: exported: comment on exported const SlirpNetwork should be of the form "SlirpNetwork ..." (revive)
        // CIDR is intentionally hardcoded to 192.168.5.0/24, as each of QEMU has its own independent slirp network.
        ^
```

</details>

### CODE REVIEW

**Comment by jandubois** [comment]
I don't really like that it forces the style on exported constants and struct fields as well.

I guess I would be fine with it if it only applied to comments on a line by itself, but not to comments on the same line as the constant or field definition; it just feels redundant and eats up horizontal space, e.g.

```diff
-	SerialVirtioLog      = "serialv.log" // virtio serial
+ 	SerialVirtioLog      = "serialv.log" // SerialVirtioLog is virtio serial
```

I probably would feel differently if we had comprehensive comments on all exported symbols, but we don't.

I couldn't find any way to enforce the comment style only for functions. Not sure what to do now.

**Comment by alexandear** [comment]
> I don't really like that it forces the style on exported constants and struct fields as well.

I added the exclude rule and reverted changes on constants:

```yaml
  # Disable revive.exported for constants.
  - text: "exported: comment on exported const"
    linters:
    - revive
```

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
