### PR TITLE
Hostresolver: Treat AAAA queries as A queries when IPv6 is disabled

### PR DESCRIPTION
**Pull request by jandubois**
A "correct" answer would be to set `handled = true` and return a NODATA response.

Unfortunately some older resolvers use a slow random source to set the transaction id.

This creates a problem on M1 computers, which are too fast for that implementation:

Both the A and AAAA queries might end up with the same id. Returning NODATA for AAAA is faster, so would arrive first, and be treated as the response to the A query.

To avoid this, we will treat an AAAA query as an A query when IPv6 has been disabled.

This way it is either a valid response for an A query, or the A records will be discarded by a genuine AAAA query, resulting in the desired NODATA response.

Packet capture with the old implementation:

```
    1   0.000000 192.168.5.15 → 192.168.5.2  DNS 81 Standard query 0x0edd A mirrorlist.centos.org
    2   0.000020 192.168.5.15 → 192.168.5.2  DNS 81 Standard query 0x0edd AAAA mirrorlist.centos.org
    3   0.000288  192.168.5.2 → 192.168.5.15 DNS 81 Standard query response 0x0edd AAAA mirrorlist.centos.org
    4   0.003276  192.168.5.2 → 192.168.5.15 DNS 303 Standard query response 0x0edd A mirrorlist.centos.org A 67.219.148.138 A 18.225.36.18 A 35.180.43.213 A 85.236.43.108 A 147.75.69.225 A 147.75.83.237
```

You can see both queries use the same transaction id `0x0edd`, so the NODATA response in frame 3 is treated as the answer to the query in frame 1. Getting a second answer in frame 4 with different content is then considered an error:

```
curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```

With the changes in the PR the packet capture looks like this:

```
    1   0.000000 192.168.5.15 → 192.168.5.2  DNS 81 Standard query 0x8064 A mirrorlist.centos.org
    2   0.000011 192.168.5.15 → 192.168.5.2  DNS 81 Standard query 0x8064 AAAA mirrorlist.centos.org
    3   0.172135  192.168.5.2 → 192.168.5.15 DNS 303 Standard query response 0x8064 A mirrorlist.centos.org A 147.75.83.237 A 18.225.36.18 A 35.180.43.213 A 67.219.148.138 A 85.236.43.108 A 147.75.69.225
    4   0.172158  192.168.5.2 → 192.168.5.15 DNS 303 Standard query response 0x8064 AAAA mirrorlist.centos.org A 147.75.83.237 A 18.225.36.18 A 35.180.43.213 A 67.219.148.138 A 85.236.43.108 A 147.75.69.225
```

So the A and AAAA queries still use the same transaction id, but since both responses contain the same requested data, the query succeeds and no error is reported.

Fixes https://github.com/rancher-sandbox/rancher-desktop/issues/1788 (and probably a couple of other DNS issues on M1 machines)

<hr>

Shoutout to fellow packet log connoisseurs @chancez, @jsoref, and @nino-k for their help and the 570 message discussion on Slack!  😄

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by carlosonunez** [comment]
Alright, I've built the latest version of `lima` and am putting it through the paces. I'll let you know how it fares in a few days when I have more data!

**Comment by carlosonunez** [comment]
Unfortunately, I'm still encountering very high DNS latency in my simple test. Here's a comparison between two image pulls of the `selenium/standalone-chrome-debug` Docker image:

## with `useHostResolver: false`

```
$: time docker pull selenium/standalone-chrome-debug:latest
latest: Pulling from selenium/standalone-chrome-debug
da7391352a9b: Pull complete
14428a6d4bcd: Pull complete
2c2d948710f2: Pull complete
ec2bb7b8cfcf: Pull complete
72c74524b7d9: Pull complete
e95b037711cc: Pull complete
9e29948e1cc8: Pull complete
d78b0ec6f93b: Pull complete
9b17ca1ca0e1: Pull complete
b90dd6cf4c3a: Pull complete
2c2cf0378d87: Pull complete
619d6d13928d: Pull complete
d6980aa31e6d: Pull complete
4afbf4c86318: Pull complete
09d5141a5571: Pull complete
7678572f4c71: Pull complete
58292a24ab09: Pull complete
43fe2b7c4466: Pull complete
ccc0ee5ae5ae: Pull complete
17b1b93543ce: Pull complete
df9057a165f3: Pull complete
279323f9c697: Pull complete
2547270e0b8a: Pull complete
dd473c9242a0: Pull complete
d71a31c83cd9: Pull complete
7a7a638c1443: Pull complete
b6d9919dcbc1: Pull complete
847edbc2c92a: Pull complete
3932171e9225: Pull complete
701dff852387: Pull complete
Digest: sha256:0c59037d0a095d7edb7b956e95a24573a6a441654a1acd2f7bebad048ef16e65
Status: Downloaded newer image for selenium/standalone-chrome-debug:latest
docker.io/selenium/standalone-chrome-debug:latest

real    0m16.905s
user    0m0.039s
sys     0m0.025s
```

## with `useHostResolver: false`


```
$: time docker pull selenium/standalone-chrome-debug:latest
latest: Pulling from selenium/standalone-chrome-debug
da7391352a9b: Pull complete
14428a6d4bcd: Pull complete
2c2d948710f2: Pull complete
ec2bb7b8cfcf: Pull complete
72c74524b7d9: Pull complete
e95b037711cc: Pull complete
9e29948e1cc8: Pull complete
d78b0ec6f93b: Pull complete
9b17ca1ca0e1: Pull complete
b90dd6cf4c3a: Pull complete
2c2cf0378d87: Pull complete
619d6d13928d: Pull complete
d6980aa31e6d: Pull complete
4afbf4c86318: Pull complete
09d5141a5571: Pull complete
7678572f4c71: Pull complete
58292a24ab09: Pull complete
43fe2b7c4466: Pull complete
ccc0ee5ae5ae: Pull complete
17b1b93543ce: Pull complete
df9057a165f3: Pull complete
279323f9c697: Downloading
2547270e0b8a: Download complete
dd473c9242a0: Download complete
d71a31c83cd9: Downloading
7a7a638c1443: Downloading
b6d9919dcbc1: Download complete
847edbc2c92a: Download complete
3932171e9225: Download complete
701dff852387: Download complete
dial tcp: lookup registry-1.docker.io on 192.168.5.3:53: read udp 192.168.5.15:58332->192.168.5.3:53: i/o timeout

real    3m30.983s
user    0m0.059s
sys     0m0.040s
```

**Comment by jsoref** [comment]
Can you please file a new issue for this?

**Comment by carlosonunez** [comment]
sorry; posted into the wrong thread.

**Pull request merged**
