### PR TITLE
Update almalinux 9 sample to 9.4

### PR DESCRIPTION
**Pull request by fwilhe2**
Updated images are available

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, would you want to update rocky and oraclelinux too?

**Comment by AkihiroSuda** [comment]
ping @fwilhe2

**Comment by afbjorklund** [comment]
> Out of curiously: Is there an api to automate this process?

Not yet.

* https://github.com/lima-vm/lima/issues/1347

It is not super important, since once you update the image the result will be the same (and it can be done at boot).
But it saves bandwidth, not having to download an outdated image with outdated packages only to update it...

**Review by AkihiroSuda — APPROVED** [review]
Merging, other images can be updated by somebody else who is interested in

**Pull request merged**
