### PR TITLE
CI: update Go (1.20)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Depends on
- https://github.com/golangci/golangci-lint/pull/3414

### CODE REVIEW

**Comment by balajiv113** [comment]
Should we update go.mod as well ??

**Comment by afbjorklund** [comment]
> Should we update go.mod as well ??

The go.mod is the _minimum_ version

**Review by balajiv113 — APPROVED** [review]
LGTM 👍

**Comment by AkihiroSuda** [comment]
Cirrus CI is down and can't be restarted 😞

**Comment by jandubois** [comment]
> Cirrus CI is down and can't be restarted 😞

Should be coming back shortly; they moved to a different GCE region because the old one was running out of available resources.

**Pull request merged**
