### PR TITLE
docs: add sequence diagram

### PR DESCRIPTION
**Pull request by samuelkarp**
I've put together a sequence diagram showing how Lima works based on a read-through of the code.  I'm not sure everything in here is fully accurate (especially around network/port forwarding and filesystem sharing), so I'm happy to change anything that is incorrect.  I hope this is helpful to others who'd like to know more about Lima!

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Could you insert the image to `docs/internal.md`, and explain the corresponding Lima version (0.8.3)?

I also prefer inline mermaid over PNG, but that can be another PR and can be done by somebody else
https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by jandubois** [comment]
I think it would be helpful to include the commands to regenerate the image in the `Makefile`, so anybody can upgrade the diagram.

**Comment by samuelkarp** [comment]
> Could you insert the image to docs/internal.md, and explain the corresponding Lima version (0.8.3)?

Done

> I think it would be helpful to include the commands to regenerate the image in the Makefile, so anybody can upgrade the diagram.

Done

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
