### PR TITLE
templates: update Fedora to 38

### PR DESCRIPTION
**Pull request by cpach**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, but please update podman, apptainer, etc. at once
https://github.com/search?q=org%3Alima-vm+Fedora-Cloud-Base-37-1.7&type=code

**Comment by cpach** [comment]
@AkihiroSuda done 🙂

**Comment by AkihiroSuda** [comment]
Could you squash commits?

**Comment by cpach** [comment]
@AkihiroSuda done!

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
