### PR TITLE
go.mod: downgrade pkg/sftp to v1.12.0 (fix `nerdctl run -v` hang up)

### LINKED ISSUE #187: Freezing when trying to map a volume
Using the default configuration, lima/nerdctl/containerd is freezing when I run a container with `-v`. Running the container without mapping a volume works fine, but as soon as I add the `-v` flag, nerdctl freezes when trying to start it.

## To reproduce
* `brew install lima`
* `limactl start` (using default configuration)
* `lima nerdctl run --rm -it -v $PWD:/app alpine`
* At this point, lima freezes entirely - does not respond to ^C, ^Z, or the like. Only way to exit out of it is with the SSH escape (`~.`).

## Full logs
```
╭─ ~/code/lima-testing
╰─❯ cat index.html 
This is a test!

╭─ ~/code/lima-testing
╰─❯ lima                            
kopinsky@lima-default:/Users/kopinsky/code/lima-testing$ cat index.html 
This is a test!
kopinsky@lima-default:/Users/kopinsky/code/lima-testing$ nerdctl run --rm -it alpine
/ # uname -a
Linux ec71a982be17 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 Linux
/ # 
kopinsky@lima-default:/Users/kopinsky/code/lima-testing$ nerdctl --debug-full run --rm -it alpine
DEBU[0000] rootless parent main: executing "/usr/bin/nsenter" with [-r/ -w/Users/kopinsky/code/lima-testing --preserve-credentials -m -n -U -t 798 -F nerdctl --debug-full run --rm -it alpine] 
DEBU[0000] found CNI isolation plugin                   
/ # uname -a
Linux f761dc56f016 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 Linux
/ # 
kopinsky@lima-default:/Users/kopinsky/code/lima-testing$ nerdctl --debug-full run --rm -it -v $PWD:/app alpine
DEBU[0000] rootless parent main: executing "/usr/bin/nsenter" with [-r/ -w/Users/kopinsky/code/lima-testing --preserve-credentials -m -n -U -t 798 -F nerdctl --debug-full run --rm -it -v /Users/kopinsky/code/lima-testing:/app alpine] 
```

Relevant output from `lima ps auxf`:
```
root         711  0.0  0.1  13288  7104 ?        Ss   21:14   0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
root        1552  0.0  0.2  14856  9152 ?        Ss   21:14   0:00  \_ sshd: kopinsky [priv]
kopinsky    1679  0.0  0.1  15016  6300 ?        S    21:14   0:00      \_ sshd: kopinsky@pts/0,pts/1
kopinsky    1693  0.0  0.0 301552  3336 ?        Ssl  21:14   0:00          \_ sshfs :/Users/kopinsky /Users/kopinsky -o slave -o ro -o allow_root
kopinsky    1708  0.0  0.0 162148  3116 ?        Ssl  21:14   0:00          \_ sshfs :/tmp/lima /tmp/lima -o slave -o allow_root
kopinsky    1939  0.0  0.1  10460  5392 pts/0    Ss   21:16   0:00          \_ bash --login
kopinsky    2351  0.2  0.5 724624 23612 pts/0    Sl+  21:17   0:00          |   \_ nerdctl --debug-full run --rm -it -v /Users/kopinsky/code/lima-testing:/app alpine
kopinsky    2362  0.0  0.0  11864  3688 pts/1    Rs+  21:19   0:00          \_ ps auxf
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
ref: lima-vm/sshocker#14 , pkg/sftp#466

Fix #187 (`Freezing when trying to map a volume`)
Fix containerd/nerdctl#338 (`nerdctl run with -v option got stuck without any explicit errors`)

The issue #187 was regression in Lima v0.6.1 (commit fccd9e0bd170c334b0f7847b9493b2101676e43c)

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
I'll release v0.6.3 right after merging this

**Comment by jandubois** [comment]
I'm testing using `/tmp/lima` and it is has weird permissions:

```console
$ ls -ld /tmp/lima
drwxr-xr-x  3 jan  wheel  96  4 Sep 14:42 /tmp/lima
$ lima ls -ld /tmp/lima
drwxr-xr-x 1 root root 96 Sep  4 21:42 /tmp/lima
```

I can create files manually inside the instance with `touch` and `mkdir`, but they end up being owned by root:

```console
jan@lima-default:/tmp/lima$ mkdir foo
jan@lima-default:/tmp/lima$ touch bar
jan@lima-default:/tmp/lima$ ls -l
total 8
-rw-r--r-- 1 root root   0 Sep  4 21:51 bar
drwxr-xr-x 1 root root  64 Sep  4 21:51 foo
drwxr-xr-x 1 root root 288 Sep  4 21:49 xxx
```

But when I try to write to the directory from `nerdctl` it fails:

```console
jan@lima-default:/tmp/lima$ nerdctl run -v /tmp/lima:/mnt screen-static-coreos:latest cp -v /home/core/screen-4.8.0/screen /mnt
cp: cannot stat '/mnt/screen': Permission denied
```

**Comment by AkihiroSuda** [comment]
Is that new in this PR?

**Comment by jandubois** [comment]
> Is that new in this PR?

No, looks like it has been like this before. But it still means that you can't write to mounted volumes from the container.

It is progress though because the container runs at all; before I wouldn't even get the permission error; it would just hang on startup.

**Comment by AkihiroSuda** [comment]
Could you open a separate issue after merging this

**Comment by jandubois** [comment]
> Could you open a separate issue after merging this

Sure

**Review by jandubois — APPROVED** [review]
LGTM

**Pull request merged**
