### PR TITLE
Rename opensuse to opensuse-leap

### PR DESCRIPTION
**Pull request by afbjorklund**
Issue #2611

### CODE REVIEW

**Review by jandubois — DISMISSED** [review]
Thanks, LGTM (only verified the x86_64 checksum though)

**Comment by afbjorklund** [comment]
The current image is a rolling "symlink", so the checksums can only be done on the "Build"

```
95b20098fbb0e5456bf1529387c8b9513056405256549e9f2f9f35d367ac8c05 openSUSE-Leap-15.6-Minimal-VM.aarch64-Cloud.qcow2
95b20098fbb0e5456bf1529387c8b9513056405256549e9f2f9f35d367ac8c05  openSUSE-Leap-15.6-Minimal-VM.aarch64-15.6.0-Cloud-Build13.327.qcow2
```

And it might not be worth it, to update the URL for every build? (as in commit b9d6d6ab59183bffd15f2cbdbff66b8b8b4887ea)

**Comment by jandubois** [comment]
> And it might not be worth it, to update the URL for every build?

Yes, unfortunately only the latest build is kept, so the URLs including the build number will break frequently. I believe this is due to concerns about the space requirement for the download mirrors.

So yes, dropping the checksum is probably the right solution.

**Review by jandubois — APPROVED** [review]

**Comment by afbjorklund** [comment]
It still needs to be bumped for every OS release, like from 15.5 to 15.6 (the 42 was annoying)

**Comment by jandubois** [comment]
> It still needs to be bumped for every OS release

Yeah, that is unavoidable. We should write a script that does this automatically...

> like from 15.5 to 15.6 (the 42 was annoying)

Yes, but still better than the Windows version "numbers": 95 → 98 → 4 → 2000 → XP → 7 … 😄

**Pull request merged**
