### PR TITLE
`limactl (create|start|edit)`: add `--video=<bool>`

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Review by jandubois — APPROVED** [review]
Thanks, LGTM.

**Review by balajiv113 — APPROVED** [review]

**Comment by afbjorklund** [comment]
It was missing a bit of the "why" (it was promoted to top-level), or what happened to alternatives like VNC.

**Comment by AkihiroSuda** [comment]
> It was missing a bit of the "why" (it was promoted to top-level), 

For ease of debugging.
E.g., showing kernel panic messages without ttyS0 (on vz)

> or what happened to alternatives like VNC.

Still supported with yq mode.

**Comment by afbjorklund** [comment]
Just wondered, since it was still mentioning the performance problems on Mac when it was enabled...

**Comment by afbjorklund** [comment]
Also, I added built-in support for it in the Lima GUI so now it has both Shell (SSH) and Display (VNC)

**Pull request merged**
