### PR TITLE
Invert logo color for dark theme

### PR DESCRIPTION
**Pull request by Sea-n**
Use SVG `<style>@media (prefers-color-scheme: dark) {}</style>` syntax to change "black" to `color: white` when it's dark theme.

According to MDN [SVG <style>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/style#browser_compatibility), it's already fully supported in all browsers for 10+ years.

Please let me know if there will be some edge case I didn't aware of. (load & render the logo by other program?)

The GitHub SVG preview show it as black, please see the following image, and review the SVG source diff.

## Preview

(Above image URL is https://raw.githubusercontent.com/Sea-n/lima/master/website/static/images/logo.svg)

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, but please sign the commit for DCO
https://github.com/apps/dco

(run `git commit -a -s --amend`, and make sure that the `Signed-off-by: NAME <EMAIL>` line with your real name is included in the commit message)

**Comment by balajiv113** [comment]
These change impacts website (Logo in landing and other pages as well is not displayed) 
https://deploy-preview-1885--lima-vm.netlify.app

Maybe possibly website needs some change / cleanups to support dark theme

**Comment by Sea-n** [comment]
How can I missed the failed CI jobs for DCO app 😅

Added `Signed-off-by` line, thank you @AkihiroSuda!

**Comment by Sea-n** [comment]
I searched for "logo" in this repo, and found 3 svg files:

### A. docs/images/lima-logo-01.svg
This seems to be old document in this repo, moved to website two weeks ago. 😜
So I keep this logo untouched.

### B. website/assets/icons/logo.svg
This file is used by Hugo navbar. Keep it untouched as well.

### C. website/static/images/logo.svg
This logo is used in cover page. And the README refer to this path.
I changed this `logo.svg` to white/black (dynamic) version, and add a `logo-black.svg` for light-theme-only pages.

Thanks @balajiv113 for pointing out the use of this logo image!
How do you guys think about this solution? I'm not familiar with Lima yet. 😅

**Comment by afbjorklund** [comment]
I'm pretty sure we called it "white" and not "black"

**Comment by Sea-n** [comment]
Fixed by 76fbb32.

**Pull request closed without merging**
