### PR TITLE
Add warnings for experimental features

### PR DESCRIPTION
**Pull request by AkihiroSuda**
ref: https://github.com/lima-vm/lima/blob/master/docs/experimental.md

### CODE REVIEW

**Review by balajiv113 — APPROVED** [review]
LGTM 👍

**Comment by afbjorklund** [comment]
How does one remove the warnings ? When are features graduated to non-experimental ?

**Comment by afbjorklund** [comment]
Not saying that these features are not experimental or that the warning is not warranted :-)

**Comment by AkihiroSuda** [comment]
> How does one remove the warnings ? When are features graduated to non-experimental ?

Yes

**Pull request merged**
