### PR TITLE
Update fedora template to f41

### PR DESCRIPTION
**Pull request by subpop**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by AkihiroSuda** [comment]
CI is failing:
https://github.com/lima-vm/lima/actions/runs/11577435687/job/32232565275?pr=2821
```
TEST| [INFO] Testing home bind mount ("/home/runner/lima-container-engine-test-tmp")
+ limactl shell fedora nerdctl pull --quiet ghcr.io/containerd/alpine:3.14.0
time="2024-10-29T16:52:08Z" level=warning msg="treating lima version \"d08c206\" from \"/home/runner/.lima/fedora/lima-version\" as very latest release"
+ echo random-content-11144
++ cat /home/runner/lima-container-engine-test-tmp/random
+ expected=random-content-11144
++ limactl shell fedora nerdctl run --rm -v /home/runner/lima-container-engine-test-tmp/random:/mnt/foo ghcr.io/containerd/alpine:3.14.0 cat /mnt/foo
time="2024-10-29T16:52:12Z" level=warning msg="treating lima version \"d08c206\" from \"/home/runner/.lima/fedora/lima-version\" as very latest release"
time="2024-10-29T16:52:13Z" level=fatal msg="failed to get unprivileged mount flags for \"/home/runner/lima-container-engine-test-tmp/random\": stat /home/runner/lima-container-engine-test-tmp/random: no such file or directory"
```

Similar to:
- https://github.com/lima-vm/lima/issues/2701

**Comment by AkihiroSuda** [comment]
Quite weird
```console
[suda@lima-fedora lima-container-engine-test-tmp]$ cat random
cat: random: No such file or directory
[suda@lima-fedora lima-container-engine-test-tmp]$ sudo cat random
random-content-19795
[suda@lima-fedora lima-container-engine-test-tmp]$ sudo mount -o remount /home/suda
[suda@lima-fedora lima-container-engine-test-tmp]$ cat random 
random-content-19795
```

**Comment by AkihiroSuda** [comment]
Fedora 41's kernel 6.11 causes QEMU to segfault?

```bash
cd $HOME
rm -rf foo bar
mkdir foo bar
touch foo/foo
limactl shell $INST cat $HOME/foo/foo
rm -rf foo
touch bar/bar
limactl shell $INST cat $HOME/bar/bar
# output: "cat: /home/suda/bar/bar: Is a directory"
limactl shell $INST ls $HOME/bar/bar
# output: (none, QEMU segfaults here)
```
(Tested on Ubuntu 24.10 x86_64, QEMU emulator version 9.0.2 (Debian 1:9.0.2+ds-4ubuntu5)

**Comment by AkihiroSuda** [comment]
Looks like we are hitting the kernel bug introduced in v6.9-rc1, fixed in v6.12-rc5: `Revert "fs/9p: simplify iget to remove unnecessary paths"` https://github.com/torvalds/linux/commit/be2ca38

**Comment by subpop** [comment]
> Looks like we are hitting the kernel bug introduced in v6.9-rc1, fixed in v6.12-rc5: `Revert "fs/9p: simplify iget to remove unnecessary paths"` [torvalds/linux@be2ca38](https://github.com/torvalds/linux/commit/be2ca38)

Hm. This is interesting. Fedora tends not to respin their images after releasing. So that leaves us in a weird position. Can we mitigate this at all in the lima template? If not, we could consider requesting a new cloud image with an updated kernel (once the fix is released). I don't know whether this would be considered significant enough to get approved.

**Pull request closed without merging**
