### PR TITLE
Update `inject-cmdline-to-template.sh`

### PR DESCRIPTION
**Pull request by norio-nomura**
- use `limactl edit` instead of `yq -i`
- simplify `yq` filter
- add `armv7l` and `riscv64` to arch
- change `default_cmdline` for minimal flavor  
  use `root=/dev/vda1` instead of `root=LABEL=cloudimg-rootfs` to avoid failing boot
  ```console
  [    0.127771] /dev/root: Can't open blockdev
  [    0.127797] VFS: Cannot open root device "LABEL=cloudimg-rootfs" or unknown-block(0,0): error -6
  [    0.127908] Please append a correct "root=" boot option; here are the available partitions:
  ```
- ~~inject provision[0].script `systemctl enable systemd-time-wait-sync.service`  
  Booting with a kernel image lacks an RTC, so time synchronization is needed to prevent network errors.~~

### CODE REVIEW

**Comment by norio-nomura** [comment]
> - inject provision[0].script `systemctl enable systemd-time-wait-sync.service`  

Removed the above and instead opened #2894

**Comment by AkihiroSuda** [comment]
What is the problem with `root=LABEL=cloudimg-rootfs`?

**Comment by norio-nomura** [comment]
> What is the problem with `root=LABEL=cloudimg-rootfs`?

The kernel image with minimal flavor image fails to boot:
```console
[    0.127771] /dev/root: Can't open blockdev
[    0.127797] VFS: Cannot open root device "LABEL=cloudimg-rootfs" or unknown-block(0,0): error -6
[    0.127908] Please append a correct "root=" boot option; here are the available partitions:
```

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by norio-nomura** [comment]
Thanks! 🙏🏻

**Pull request merged**
