### PR TITLE
CI: add back archlinux

### LINKED ISSUE #2701: ArchLinux + 9p fails on GitHub Actions (but not on local MacBook): `failed to get unprivileged mount flags for \"/home/runner/lima-container-engine-test-tmp/random\": stat /home/runner/lima-container-engine-test-tmp/random: no such file or directory`
```
level=fatal msg="failed to get unprivileged mount flags for \"/home/runner/lima-container-engine-test-tmp/random\": stat /home/runner/lima-container-engine-test-tmp/random: no such file or directory"
```

https://github.com/lima-vm/lima/pull/1953/files/88cca7543122b694b7392e25816676779b9f38a3#r1790627760

### LINKED ISSUE #2714: ArchLinux CI is failing since 2024-10-10 (due to the update of the `cloud-init` package)
**EDIT**: this is a regression in cloud-init 24.3.1-1
https://gitlab.archlinux.org/archlinux/packaging/packages/cloud-init/-/issues/3

- - -
https://github.com/lima-vm/lima/actions/runs/11263406944/job/31321212683

```
time="2024-10-09T22:01:04Z" level=info msg="[hostagent] Waiting for the essential requirement 2 of 4: \"user session is ready for ssh\""
time="2024-10-09T22:01:44Z" level=info msg="[hostagent] Waiting for the essential requirement 2 of 4: \"user session is ready for ssh\""
time="2024-10-09T22:02:24Z" level=info msg="[hostagent] Waiting for the essential requirement 2 of 4: \"user session is ready for ssh\""
time="2024-10-09T22:02:52Z" level=fatal msg="did not receive an event with the \"running\" status"
Error: ERROR] Failed to start "archlinux"
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #2714
Fix #2701

### CODE REVIEW

**Comment by jandubois** [comment]
Isn't the cloud-init bug still present?

**Comment by AkihiroSuda** [comment]
Yes, it is still failing, although the error logs seem to have changed:

https://github.com/lima-vm/lima/actions/runs/11598975077/job/32296080408?pr=2823
```
==> /home/runner/.lima/archlinux/serial.log <==
[  OK  ] Started Serial Getty on hvc0.
[  OK  ] Started Serial Getty on ttyS0.
[  OK  ] Reached target Login Prompts.
         Starting User Manager for UID 1001...
[  OK  ] Finished Cloud-init: Config Stage.
[  OK  ] Started User Manager for UID 1001.
Arch Linux 6.11.5-arch1-1 (ttyS0)
lima-archlinux login: [   37.976911] sh[587]: nc.openbsd: /run/cloud-init/share/final-return.sock: No such file or directory
==> /home/runner/.lima/archlinux/serialv.log <==
┌────────────────────────────────────────────────────────────────────────────────────────────────┐││││││││││││││││││││││││││││││││││││││└────────────────────────────────────────────────────────────────────────────────────────────────┘     Use the ▲ and ▼ keys to select which entry is highlighted.                              
      Press enter to boot the selected OS, `e' to edit the commands before booting or `c' for 
      a command-line.                                                                          *Arch Linux                                                                                      Advanced options for Arch Linux                                                                 UEFI Firmware Settings                                                                         
Loading Linux linux ...
Loading initial ramdisk ...
Arch Linux 6.11.5-arch1-1 (hvc0)
lima-archlinux login: + limactl shell archlinux systemctl --no-pager status
time="2024-10-30T18:30:17Z" level=warning msg="treating lima version \"d425dfe\" from \"/home/runner/.lima/archlinux/lima-version\" as very latest release"
bash: line 1: cd: /home/runner/work/lima/lima: No such file or directory
● lima-archlinux
    State: running
    Units: 340 loaded (incl. loaded aliases)
     Jobs: 0 queued
   Failed: 0 units
[...]
```

**Comment by jandubois** [comment]
> bash: line 1: cd: /home/runner/work/lima/lima: No such file or directory

That happens when the directory isn't mounted, or if there are symlinks involved:

```console
$ ls -l ~/suse
lrwxr-xr-x  1 jan  staff  26  7 Feb  2020 /Users/jan/suse -> /Volumes/ThunderBlade/suse
$ limactl shell ubuntu-22.04
bash: line 1: cd: /Users/jan/suse/lima: No such file or directory
```

That's why I normally have a mount for `/Volumes/ThunderBlade` in my `defaults.yaml`, so the symlink works inside the VMs too.

Anyways, I just checked, and Arch has no `/usr/bin/nc` nor `/usr/bin/nc.openbsd`, so unless you downgrade cloud-init, it should still have problems.

**Comment by jandubois** [comment]
Sorry, I somehow missed this; the error was right there in the logs:

```
nc.openbsd: /run/cloud-init/share/final-return.sock: No such file or directory
```

Which is what is discussed in https://github.com/lima-vm/lima/issues/2714#issuecomment-2404674254

**Comment by AkihiroSuda** [comment]
Now green

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

Confirmed:

```console
[jan@lima-archlinux jan]$ ls -l /usr/bin/nc*
-rwxr-xr-x 1 root root 39448 Oct 24 13:24 /usr/bin/nc
lrwxrwxrwx 1 root root     2 Oct 24 13:24 /usr/bin/nc.openbsd -> nc
-rwxr-xr-x 1 root root  8557 May 24 23:43 /usr/bin/ncursesw6-config
```

**Pull request merged**
