### PR TITLE
Add possibility to override /tmp

### LINKED ISSUE #2339: Add abstraction for the default `/tmp/lima` directory ?
### Description

It doesn't work so great in a multi-user environment, and doesn't work on Windows (compared with e.g. `C:\TEMP`)

i.e. when several users are sharing a server, they will see the files from the other users in the shared `/tmp/lima`

Hosts based on Fedora put `/tmp` [in RAM](https://fedoraproject.org/wiki/Features/tmp-on-tmpfs), so you need to use `/var/tmp` if you want to use a normal disk directory.

Should we have some placeholder value for the default.yaml, instead of the "/tmp/lima"? Similar to LIMA_HOME.

* https://github.com/lima-vm/lima/pull/2337#issuecomment-2106195608

### PR DESCRIPTION
**Pull request by afbjorklund**
Use `$TMPDIR` to change the location of `/tmp` on Unix.

Use `$TEMP` to change the location of `/tmp` on Windows.

https://pkg.go.dev/os#TempDir

Closes #2339

### CODE REVIEW

**Comment by afbjorklund** [comment]
On second thought, having `/var/tmp/lima` mount under `/tmp/lima` breaks the abstraction.

We probably still need to do something different on Windows, and not use **local**pathutil?

**Comment by afbjorklund** [comment]
Reference to the `cygpath` utility, regarding filepath translation...

https://www.msys2.org/docs/filesystem-paths/ (skipped the /mnt)

**Comment by jandubois** [comment]
> No idea where `C:\Users\UserName\AppData\Local\Temp\lima` is supposed to end up.
> 
> Possibly something like `/c/Users/UserName/AppData/Local/Temp/lima`, maybe `/mnt`

I have not really used Lima on Windows yet, but aren't we using WSL2 for the emulation? In that case we should be using WSL2 path names and not msys hacks.

Note that with WSL2 (depending on how it is configured) none of our mounting really matters as everything is already mounted anyways:

```console
suse@rd-w11-test-1:~$ wslpath -u c:\\user
/mnt/c/user
suse@rd-w11-test-1:~$ wslpath -w /tmp
\\wsl.localhost\Ubuntu-22.04\tmp
```

**Comment by afbjorklund** [comment]
This was having the eye towards QEMU (or Hyper-V perhaps), but mostly it was just a unit test failure.

**Comment by afbjorklund** [comment]
Then again, this feature is really on needed on Fedora or on Windows (i.e. without WSL)

It is not needed on Ubuntu or on macOS, so I think I will just leave it in "draft" for a while

**Pull request closed without merging**
