### PR TITLE
CI: drop Go 1.20

### PR DESCRIPTION
**Pull request by AkihiroSuda**
1.20 has already reached EOL

### CODE REVIEW

**Comment by vasileknik76** [comment]
Should we also update `1.20` to `1.21` in [website/go.mod](https://github.com/lima-vm/lima/blob/master/website/go.mod#L3)?

**Comment by afbjorklund** [comment]
The new go toolchain has some crazy auto-updating feature, if you bump go.mod

**Comment by AkihiroSuda** [comment]
> Should we also update `1.20` to `1.21` in [website/go.mod](https://github.com/lima-vm/lima/blob/master/website/go.mod#L3)?

I don't know how to update that file.
`go mod tidy` erases all the modules in the file.

**Comment by vasileknik76** [comment]
> I don't know how to update that file. `go mod tidy` erases all the modules in the file.

It seems `go.mod` is not used in `website` directory, so it can be removed.

**Pull request merged**
