### PR TITLE
aarch64: unset highmem=off for QEMU >= 7.0

### LINKED ISSUE #680: Memory allocation fails on darwin arm64 with latest qemu
### Description

Starting the default with 4GiB fails:
`qemu-system-aarch64: Addressing limited to 32 bits, but memory exceeds it by 1073741824 bytes`

Need to reduce memory, to e.g. 2GiB.

Since https://github.com/qemu/qemu/commit/3715c251cc781b263fbd7f7c535fde7a4da401c3

Most likely the `highmem=off` parameter to qemu should be parametrized, and not used with later versions.

The reasons that caused it to be needed (for ARM) earlier, seems to no longer be true with QEMU 7.0.

This was: `QEMU emulator version 6.2.50 (v6.1.0-3974-gf6620d0b34-dirty)`

### PR DESCRIPTION
**Pull request by AkihiroSuda**
- QEMU >= 7.0 requires highmem=off NOT to be set, otherwise fails with "Addressing limited to 32 bits, but memory exceeds it by 1073741824 bytes"
- QEMU <  7.0 requires highmem=off to be set, otherwise fails with "VCPU supports less PA bits (36) than requested by the memory map (40)"

See #680 and #24

Fix #680

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Tested on Intel Mac, with qemu/qemu@2ad7624900

@jandubois @afbjorklund PTAL

**Review by jandubois — DISMISSED** [review]
I haven't tested it, but LGTM.

**Comment by AkihiroSuda** [comment]
Can anybody test this with M1 macOS?

**Comment by afbjorklund** [comment]
> Can anybody test this with M1 macOS?

I can see if I can find a machine tonight, we're doing some testing of the minikube ISO (for aarch64)

**Comment by AkihiroSuda** [comment]
Merging and releasing v0.9.0-beta.0 for ease of testing

**Pull request merged**
