### PR TITLE
go.mod: pkg/sftp v1.13.3 (fix weird `ls -l` result)

### LINKED ISSUE #206: Containers can't write to mounted directories
From https://github.com/lima-vm/lima/pull/203#issuecomment-913046166:

I'm testing using `/tmp/lima` and it is has weird permissions:

```console
$ ls -ld /tmp/lima
drwxr-xr-x  3 jan  wheel  96  4 Sep 14:42 /tmp/lima
$ lima ls -ld /tmp/lima
drwxr-xr-x 1 root root 96 Sep  4 21:42 /tmp/lima
```

I can create files manually inside the instance with `touch` and `mkdir`, but they end up being owned by root:

```console
jan@lima-default:/tmp/lima$ mkdir foo
jan@lima-default:/tmp/lima$ touch bar
jan@lima-default:/tmp/lima$ ls -l
total 8
-rw-r--r-- 1 root root   0 Sep  4 21:51 bar
drwxr-xr-x 1 root root  64 Sep  4 21:51 foo
drwxr-xr-x 1 root root 288 Sep  4 21:49 xxx
```

But when I try to write to the directory from `nerdctl` it fails:

```console
jan@lima-default:/tmp/lima$ nerdctl run -v /tmp/lima:/mnt screen-static-coreos:latest cp -v /home/core/screen-4.8.0/screen /mnt
cp: cannot stat '/mnt/screen': Permission denied
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
v1.13.0 had a regression, but fixed in v1.13.3 (pkg/sftp#466)

Fix #206 (weird `ls -l` result)

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
???
```
==> Installing dependencies for qemu: python@3.9, libslirp, libssh, lzo, ncurses, pixman, snappy and vde
==> Installing qemu dependency: python@3.9
==> Pouring python@3.9--3.9.7.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/2to3
```

https://github.com/lima-vm/lima/pull/211/checks?check_run_id=3519012233

**Review by jandubois — APPROVED** [review]
File ownership seems correct with this PR. Group ownership is still weird (anything I create inside the VM on the mounted volume has `root` as the group owner (uid:501, gid:0). Not sure if this matters.

This PR probably needs to be rebased on `master` to get the CI fix from #212

**Comment by jandubois** [comment]
> This PR probably needs to be rebased on `master` to get the CI fix from #212

Definitely needs to be rebased:

```
==> Pouring python@3.9--3.9.7.catalina.bottle.tar.gz
454
Error: The `brew link` step did not complete successfully
455
The formula built, but is not symlinked into /usr/local
456
Could not symlink bin/2to3
457
Target /usr/local/bin/2to3
458
already exists. You may want to remove it:
459
  rm '/usr/local/bin/2to3'
```

**Comment by AkihiroSuda** [comment]
Thanks, rebased

**Pull request merged**
