### PR TITLE
limactl ls $INSTANCE should exit with non-0 status if $INSTANCE does not exist #1139

### PR DESCRIPTION
**Pull request by BajuMcBites**
- switched the warning message into an error message

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by jandubois** [comment]
I realize this PR has already been merged, but I disagree with the implementation, as it introduces a regression:

I have a single `alpine` instance running. Before this PR I get the following output:


```console
$ limactl ls foo alpine bar
WARN[0000] No instance matching foo found.
WARN[0000] No instance matching bar found.
NAME      STATUS     SSH            VMTYPE    ARCH      CPUS    MEMORY    DISK      DIR
alpine    Stopped    127.0.0.1:0    qemu      x86_64    4       4GiB      100GiB    ~/.lima/alpine
```

With this PR the command stops at the first instance that is not found:

```console
$ limactl ls foo alpine bar
FATA[0000] no instance matching foo found
```

So I think we need to record the fact that at least one requested instance was not found, but only exit with `os.Exit(1)` after the information about the existing instances (and warnings about additional missing instances) have been printed.

I would like to see this fixed in a follow-up PR.

**Comment by BajuMcBites** [comment]
Sorry about this, I did not think to account for multiple instances. I can work on another PR to fix this issue. Should it still log the "No instance matching <name> found." as warnings and then exit with 1, or is there a different message type that is preferred?

**Comment by jandubois** [comment]
> I can work on another PR to fix this issue. Should it still log the "No instance matching found." as warnings and then exit with 1

Yes, I think the output should remain unchanged, just the exit code should be non-0 when at least one instance could not be found.

The easiest way to exit with a non-0 code would be to call `os.Exit(1)`.

Note that there are multiple output formats for this command, with some early return statements. Make sure that all of them are being covered!

**Pull request merged**
