### PR TITLE
CI: see if  wsl2 works

### PR DESCRIPTION
**Pull request by AkihiroSuda**
- #1781

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
```
+ ./hack/test-templates.sh ./templates/experimental/wsl2.yaml
TEST| [INFO] Validating "./templates/experimental/wsl2.yaml"
time="2023-0[9](https://github.com/lima-vm/lima/actions/runs/6264735883/job/17012085612?pr=1826#step:7:10)-21T17:03:07Z" level=info msg="\"./templates/experimental/wsl2.yaml\": OK"
time="2023-09-21T17:03:07Z" level=warning msg="No instance found. Run `limactl create` to create an instance."
TEST| [INFO] Setup port forwarding rules for testing in "/c/Users/runneradmin/lima-config-tmp/wsl2.yaml"
time="2023-09-21T17:03:09Z" level=info msg="\"C:/Users/runneradmin/lima-config-tmp/wsl2.yaml\": OK"
TEST| [INFO] Creating "wsl2" from "/c/Users/runneradmin/lima-config-tmp/wsl2.yaml"
+ limactl create --tty=false --cpus=1 --memory=1 /c/Users/runneradmin/lima-config-tmp/wsl2.yaml
time="2023-09-21T17:03:09Z" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2023-09-21T[17](https://github.com/lima-vm/lima/actions/runs/6264735883/job/17012085612?pr=1826#step:7:18):03:09Z" level=fatal msg="errors inspecting instance: [failed to run `wsl --list --verbose`, err: exit status 0xffffffff]"
+ eval rm -rf '"/c/Users/runneradmin/lima-config-tmp";' limactl delete -f '"wsl2"'
++ rm -rf /c/Users/runneradmin/lima-config-tmp
++ limactl delete -f wsl2
time="[20](https://github.com/lima-vm/lima/actions/runs/6264735883/job/17012085612?pr=1826#step:7:21)23-09-[21](https://github.com/lima-vm/lima/actions/runs/6264735883/job/17012085612?pr=1826#step:7:22)T17:03:09Z" level=info msg="The wsl2 driver process seems already stopped"
time="2023-09-21T17:03:09Z" level=info msg="The host agent process seems already stopped"
time="20[23](https://github.com/lima-vm/lima/actions/runs/6264735883/job/17012085612?pr=1826#step:7:24)-09-21T17:03:09Z" level=info msg="Removing C:\\Users\\runneradmin\\.lima\\wsl2 under \"*.pid *.sock *.tmp\""
time="2023-09-21T17:03:09Z" level=fatal msg="failed to delete instance \"wsl2\": failed to unregister \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\": failed to run `wsl --list --verbose`, err: exit status 0xffffffff"
Error: Process completed with exit code 1.
```

https://github.com/lima-vm/lima/actions/runs/6264735883/job/17012085612?pr=1826

**Comment by AkihiroSuda** [comment]
```
  wsl --list --verbose
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
Windows Subsystem for Linux has no installed distributions.


Distributions can be installed by visiting the Microsoft Store:


https://aka.ms/wslstore
```

**Comment by AkihiroSuda** [comment]
```
Error: ERROR] Failed to start "wsl2"
+ diagnose wsl2
+ NAME=wsl2
+ set -x +e
+ tail /c/Users/runneradmin/.lima/wsl2/ha.stderr.log /c/Users/runneradmin/.lima/wsl2/ha.stdout.log
==> /c/Users/runneradmin/.lima/wsl2/ha.stderr.log <==
98.11 MiB / 98.11 MiB (100.00%) 127.47 MiB/s{"level":"info","msg":"decompressing .zst with [zstd -d]","time":"2023-09-21T18:11:18Z"}
{"level":"info","msg":"Decompressing data\n","time":"2023-09-21T18:11:18Z"}

98.11 MiB / 98.11 MiB (100.00%) ? p/s{"level":"debug","msg":"res.ValidatedDigest=true","time":"2023-09-21T18:11:18Z"}
{"level":"info","msg":"Downloaded the image from \"https://deps.runfinch.com/common/x86-64/finch-rootfs-production-amd64-1690920103.tar.zst\"","time":"2023-09-21T18:11:18Z"}
{"level":"info","msg":"Download succeeded","time":"2023-09-21T18:11:18Z"}
{"level":"info","msg":"Importing distro from \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\\\\basedisk\" to \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\"","time":"2023-09-21T18:11:18Z"}
{"level":"info","msg":"Waiting for the essential requirement 1 of 3: \"ssh\"","time":"2023-09-21T18:11:28Z"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2023-09-21T18:11:28Z"}
{"level":"debug","msg":"executing ssh for script \"ssh\": C:\\Program Files\\Git\\usr\\bin\\ssh.exe [ssh -F /dev/null -o IdentityFile=\"C:/Users/runneradmin/.lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=^aes128-gcm@openssh.com,aes256-gcm@openssh.com -o User=lima -o ControlMaster=auto -o ControlPath=\"C:/Users/runneradmin/.lima/wsl2/ssh.sock\" -o ControlPersist=yes -p 22 172.19.253.101 -- /bin/bash]","time":"2023-09-21T18:11:28Z"}

==> /c/Users/runneradmin/.lima/wsl2/ha.stdout.log <==
Downloading the image (finch-rootfs-production-amd64-1690920103.tar.zst)
{"time":"2023-09-21T18:11:28.465197Z","status":{"sshLocalPort":22}}
+ limactl shell wsl2 systemctl --no-pager status
command-line line 0: invalid quotes
+ limactl shell wsl2 systemctl --no-pager
command-line line 0: invalid quotes
+ limactl shell wsl2 sudo cat /var/log/cloud-init-output.log
command-line line 0: invalid quotes
+ set +x -e
time="2023-09-21T18:11:30Z" level=info msg="The wsl2 driver process seems already stopped"
time="2023-09-21T18:11:30Z" level=info msg="The host agent process seems already stopped"
time="2023-09-21T18:11:30Z" level=info msg="Removing C:\\Users\\runneradmin\\.lima\\wsl2 under \"*.pid *.sock *.tmp\""
time="2023-09-21T18:11:30Z" level=info msg="Removing \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\\\\ha.sock\""
time="2023-09-21T18:11:30Z" level=info msg="Unregistering WSL2 VM"
time="2023-09-21T18:11:31Z" level=info msg="Deleted \"wsl2\" (\"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\")"
Error: Process completed with exit code 1.

```

https://github.com/lima-vm/lima/actions/runs/6265448839/job/17014322683?pr=1826
https://github.com/lima-vm/lima/pull/1826/commits/fc1ace297b00f4769fa8c18e3fdd7cd5f2f8fb0b


@pendo324 PTAL

**Comment by AkihiroSuda** [comment]
```
time="2023-09-21T18:11:18Z" level=info msg="[hostagent] Importing distro from \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\\\\basedisk\" to \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\""
2023/09/21 18:11:[28](https://github.com/lima-vm/lima/actions/runs/6265448839/job/17014322683?pr=1826#step:9:29) Error in Watcher Error channel: CancelIo: The handle is invalid.
2023/09/21 18:11:28 Error in Watcher Error channel: CloseHandle: The handle is invalid.
time="2023-09-21T18:11:28Z" level=fatal msg="invalid character 'D' looking for beginning of value"
```

@pendo324 @afbjorklund Do you repro the issue locally? Is it working on your local env?

**Comment by balajiv113** [comment]
I think the error is related to using bash mode. Y not try a simple `limactl start template://` to see if its able to start fully

**Comment by AkihiroSuda** [comment]
Removed bash, still failing

```
Run .\_output\bin\limactl.exe start template://experimental/wsl2
time="2023-09-28T15:0[4](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:5):49Z" level=info msg="Terminal is not available, proceeding without opening an editor"
time="2023-09-28T1[5](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:6):04:50Z" level=warning msg="expected status \"Stopped\", got \"Uninitialized\""
time="2023-09-28T15:04:50Z" level=warning msg="Ignoring: vmType wsl2: [OS CPUs Memory Firmware Audio Video GuestInstallPrefix CACertificates Rosetta]"
time="2023-09-28T15:04:50Z" level=info msg="Attempting to download the nerdctl archive" arch=x8[6](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:7)_64 digest="sha256:2c5c43a8b[7](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:8)7ed62090241027361baa62d8fb70a759bc9e7a82c637135598701f" location="https://github.com/containerd/nerdctl/releases/download/v1.6.0/nerdctl-full-1.6.0-linux-amd64.tar.gz"
Downloading the nerdctl archive (nerdctl-full-1.6.0-linux-amd64.tar.gz)

240.55 MiB / 240.55 MiB (100.00%) ? p/stime="2023-09-2[8](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:9)T15:04:51Z" level=info msg="Downloaded the nerdctl archive from \"https://github.com/containerd/nerdctl/releases/download/v1.6.0/nerdctl-full-1.6.0-linux-amd64.tar.gz\""
time="2023-0[9](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:10)-28T15:04:52Z" level=info msg="[hostagent] hostagent socket created at C:\\Users\\runneradmin\\.lima\\wsl2\\ha.sock"
time="2023-09-28T15:04:52Z" level=info msg="[hostagent] Starting WSL VM"
time="2023-09-28T15:04:52Z" level=info msg="[hostagent] Attempting to download the image"
time="2023-09-28T15:04:53Z" level=info msg="[hostagent] 98.11 MiB / 98.11 MiB ([10](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:11)0.00%) ? p/s{\"level\":\"info\",\"msg\":\"decompressing .zst with [zstd -d]\",\"time\":\"2023-09-28T15:04:53Z\"}"
time="2023-09-28T15:04:53Z" level=info msg="[hostagent] Decompressing data\n"
time="2023-09-28T15:04:53Z" level=info msg="[hostagent] 98.[11](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:12) MiB / 98.11 MiB (100.00%) ? p/s{\"level\":\"debug\",\"msg\":\"res.ValidatedDigest=true\",\"time\":\"2023-09-28T[15](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:16):04:53Z\"}"
time="2023-09-28T15:04:53Z" level=info msg="[hostagent] Downloaded the image from \"https://deps.runfinch.com/common/x86-64/finch-rootfs-production-amd64-[16](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:17)90920103.tar.zst\""
time="2023-09-28T15:04:53Z" level=info msg="[hostagent] Download succeeded"
time="2023-09-28T15:04:53Z" level=info msg="[hostagent] Importing distro from \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\\\\basedisk\" to \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\""
time="[20](https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826#step:9:21)23-09-28T15:05:03Z" level=fatal msg="invalid character 'D' looking for beginning of value"
```
https://github.com/lima-vm/lima/actions/runs/6340681012/job/17222647981?pr=1826

**Comment by AkihiroSuda** [comment]
Added some debug prints, it tries to unmarshal `Downloading the image (finch-rootfs-production-amd64-1690920103.tar.zst)` as JSON
```
time="2023-09-28T15:24:38Z" level=info msg="[hostagent] Importing distro from \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\\\\basedisk\" to \"C:\\\\Users\\\\runneradmin\\\\.lima\\\\wsl2\""
time="[20](https://github.com/lima-vm/lima/actions/runs/6340933579/job/17223439234?pr=1826#step:9:21)23-09-28T15:24:49Z" level=fatal msg="failed to unmarshal \"Downloading the image (finch-rootfs-production-amd64-1690920103.tar.zst)\" as events.Event: invalid character 'D' looking for beginning of value"
```

@pendo324 Do you see this error locally? Is it working on your machine?

**Comment by balajiv113** [comment]
Not using logrus here, will this be a problem here ??
https://github.com/lima-vm/lima/blob/6938ae5fc8eaf1dec9a99011f775e571a37601ec/pkg/downloader/downloader.go#L444

**Comment by AkihiroSuda** [comment]
> Not using logrus here, will this be a problem here ??
> 
> https://github.com/lima-vm/lima/blob/6938ae5fc8eaf1dec9a99011f775e571a37601ec/pkg/downloader/downloader.go#L444

Yes, IIUC this was on purpose to avoid messing up the output, but probably we should use logrus, or at least switch the output to stderr.

**Comment by AkihiroSuda** [comment]
```
time="2023-09-28T17:18:46Z" level=info msg="[hostagent] Driver stopped due to error: \"error running wslCommand that executes boot.sh: exit status 127, check /var/log/lima-init.log for more details (out=\\\"bash: line 1: $'\\\\\\\\r': command not found\\\\n\\\")\""
```
https://github.com/lima-vm/lima/actions/runs/6342128771/job/17227239927?pr=1826

**Comment by AkihiroSuda** [comment]
Temporarily giving up:
- https://github.com/lima-vm/lima/pull/1866

Still help wanted to carry this.

**Comment by pendo324** [comment]
Sorry @AkihiroSuda, I just saw this for this first time (apparently I had my notifications off? I'll try to fix that).

The issue seems to be that you don't have the binaries needed to extract the rootfs archive. It works on my machine because I do have those in my path.

Is the `zstd` binary installed on the GHA runner? Is tar/gzip installed? We can switch to an OS image that uses tar/gzip if zstd is not installed.

To install tar/gzip we can install Git for Windows and add it to the path. Something like this will do that:

```powershell
$env:Path = 'C:\Program Files\Git\usr\bin;' + $env:Path
Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH -Value $env:Path
```

If you re-open this PR and change the rootfs in wsl2.yaml to this, it should work if tar/gzip are installed:

```
- location: "https://deps.runfinch.com/common/x86-64/finch-rootfs-production-amd64-1694791577.tar.gz",
  arch: "x86_64"
  digest: "sha256:2d4d2e7386450899c6d0587fd0db21afadb31d974fa744aa9365c883935c5341"
```

**Comment by AkihiroSuda** [comment]
Thanks @pendo324 would you mind opening a PR?
The error has to be human-readable too.

**Pull request closed without merging**
