### PR TITLE
nerdctl: update to v2.0.0

### PR DESCRIPTION
**Pull request by AkihiroSuda**
https://github.com/containerd/nerdctl/releases/tag/v2.0.0

### CODE REVIEW

**Comment by afbjorklund** [comment]
What about using YAML for this information ?

* https://github.com/lima-vm/lima/pull/2403

**Comment by afbjorklund** [comment]
How do you choose which version to use?

Edit the yaml template with the old digests?

**Comment by AkihiroSuda** [comment]
V2 is expected to retain compatibility.
V1 can be still installed manually with the "plain" mode

**Comment by AkihiroSuda** [comment]
This is now ready.

Will release Lima v1.0 after merging this 🎉

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

**Comment by jandubois** [comment]
> Will release Lima v1.0 after merging this 🎉

I assume this means we'll leave #2832 for Lima 1.1 and I don't have to rush to wrap it up, right?

**Comment by AkihiroSuda** [comment]
right

**Comment by AkihiroSuda** [comment]
already tagged v1.0, will make a release in a few minutes

**Pull request merged**
