### PR TITLE
nerdctl: update to v0.22.2 ; templates: update archlinux, alpine-lima

### PR DESCRIPTION
**Pull request by AkihiroSuda**
https://github.com/containerd/nerdctl/releases/tag/v0.22.1
https://github.com/containerd/nerdctl/releases/tag/v0.22.2

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Failing on Fedora

```
[suda@lima-fedora ~]$ nerdctl run -it --rm alpine
FATA[0000] failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown 
```

**Comment by afbjorklund** [comment]
It is not obvious why the windows cross unit tests are failing

```
=== RUN   TestDefaultPubKeys
    sshutil_test.go:12: found 0 public keys
--- PASS: TestDefaultPubKeys (0.02s)
=== RUN   TestParseOpenSSHVersion
--- PASS: TestParseOpenSSHVersion (0.00s)
=== RUN   Test_detectValidPublicKey
--- PASS: Test_detectValidPublicKey (0.00s)
PASS
FAIL	github.com/lima-vm/lima/pkg/sshutil	0.990s
```

pass + pass + pass = fail ?

**Comment by AkihiroSuda** [comment]
@afbjorklund Might be an issue of Wine 🍷 , idk

**Comment by afbjorklund** [comment]
> @afbjorklund Might be an issue of Wine wine_glass , idk

There were some complaints about not installing wine32 (only wine64), but I don't think we have any 32-bit binaries ?

It worked OK, for what is worth. But it did find some keys in `C:\users\anders\.lima\_config\user.pub` - maybe that was it

**Pull request merged**
