### PR TITLE
Use macOS M1 runners for CI

### PR DESCRIPTION
**Pull request by balajiv113**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
> {"level":"fatal","msg":"Error Domain=VZErrorDomain Code=2 Description=\"Invalid virtual machine configuration. Virtualization is not available on this hardware.\" UserInfo={\n    NSLocalizedFailure = \"Invalid virtual machine configuration.\";\n    NSLocalizedFailureReason = \"Virtualization is not available on this hardware.\";\n}","time":"2023-10-04T09:57:43Z"}

😥

**Comment by balajiv113** [comment]
Its as i feared.

They are also using Virtualization.Framework. So nested virtualization is not supported.

Reference: https://github.com/actions/runner-images/issues/8465

**Comment by balajiv113** [comment]
I will change it to large runner and see if its stable. Is that okay ?

**Comment by AkihiroSuda** [comment]
> I will change it to large runner and see if its stable. Is that okay ?

Tried, didn't see much difference
- https://github.com/lima-vm/lima/pull/1720

**Comment by balajiv113** [comment]
I will close this PR as nothing further to do here.

**Pull request closed without merging**
