### PR TITLE
templates: update Ubuntu to 24.04

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

**Comment by afbjorklund** [comment]
Do you have some documentation (notes), on how these updates are prepared ?

Not so much the major bump, from 22.04 to 24.04, but the checksums and such

* https://github.com/lima-vm/lima/issues/1347

* https://github.com/lima-vm/lima/issues/824

**Comment by AkihiroSuda** [comment]
Just updated manually, currently 😞

**Comment by afbjorklund** [comment]
This is a nice feature, of the new release:

https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890#public-cloud-cloud-images-83

> The footprint of minimal images has been reduced

```diff
-619M	ubuntu-22.04-server-cloudimg-amd64.img
+454M	ubuntu-24.04-server-cloudimg-amd64.img
```
```
422M	debian-12-generic-amd64.qcow2
329M	debian-12-genericcloud-amd64.qcow2
```

**Comment by afbjorklund** [comment]
New image tested OK here, as well.

I think the results from the k8s template is very good, starts a vanilla kubeadm cluster in 10 seconds:

```
[  168.382775] cloud-init[1813]: [init] Using Kubernetes version: v1.30.0

[  170.835847] cloud-init[1813]: [kubelet-start] Starting the kubelet
[  171.584115] cloud-init[1813]: [kubelet-check] The kubelet is healthy after 503.076679ms

[  171.584470] cloud-init[1813]: [api-check] Waiting for a healthy API server. This can take up to 4m0s
[  176.088824] cloud-init[1813]: [api-check] The API server is healthy after 4.503997398s

[  177.523608] cloud-init[1813]: Your Kubernetes control-plane has initialized successfully!
```

Slightly longer to pull the required images and deploy the coredns addon, but still. (for all else, k3s)

**Pull request merged**
