### PR TITLE
pkg: move regexp compilation out of loops

### PR DESCRIPTION
**Pull request by alexandear**
This PR moves regexps out of `for` loops to recompile only once per function call.

### CODE REVIEW

**Comment by jandubois** [comment]
> to prevent it from being recompiled each time these functions are called

All these regexes are only used once, or very few times, so the time spent recompiling them is immaterial.[^1]

[^1]: And if you are using VZ emulation instead of QEMU, then you now compile a regex that otherwise you wouldn't. Others may also be unused, depending on the subcommand you are running. None of this matters, of course.

On the other hand, you now introduce additional global variables with longer names in a wider scope, and the actual text of the regex is now further away in the source code from the location where is being used.

Making the code even slightly harder to understand/maintain is not worth it to me to get a non-noticeable performance gain.

I don't feel strongly about this particular instance, so I'll leave it to other maintainers to decide if they want to accept this change.

**Comment by afbjorklund** [comment]
Moving it out of the loops sounds good (if loops are long), not sure about making it global (as mentioned above)

**Comment by AkihiroSuda** [comment]
What's the current status?

**Comment by AkihiroSuda** [comment]
@alexandear (Off-topic: what's your CNCF slack ID?)

**Review by jandubois — DISMISSED** [review]
As I wrote before, I'm not sure if creating global variables for regular expressions that are likely only compiled once per program run is an improvement, but at least the definition is still reasonably close to the location where it is used.

If other @lima-vm/maintainers want to merge, then I'm fine with it.

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

**Comment by alexandear** [comment]
> @alexandear (Off-topic: what's your CNCF slack ID?)

https://cloud-native.slack.com/team/U075V4TMQPM

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
