### PR TITLE
Unify file and dir names; integrate ls-lint

### PR DESCRIPTION
**Pull request by alexandear**
The PR:

- renames Go files in the `cmd` to match `kebab-case` for consistency;
- renames `pkg/networks/usernet/UDPFileConn.go` to `pkg/networks/usernet/udpfileconn.go`
- renames directories in `website/content` to be lowercase;
- integrates [`ls-lint`](https://ls-lint.org/) to ensure proper file and directory names in the future.

### CODE REVIEW

**Comment by afbjorklund** [comment]
I always found it annoying that the links and the files don't match, in the "website"

**Review by jandubois — CHANGES_REQUESTED** [review]
I don't understand why `factory-reset.go` was renamed to `factory-reset_test.go`; it is not a test file.

That also breaks building the app:

```
undefined: newFactoryResetCommand
```

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

Since this is largely based on personal preferences, I'll leave the merging to somebody else from @lima-vm/maintainers to give them a chance to object to it.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
