### PR TITLE
Follow-up to "Implement unix socket forwarding"

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Follow up to #369

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
```console
$ DOCKER_HOST=unix://$HOME/docker.sock docker run -it --rm alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:385: applying cgroup configuration for process caused: error while starting unit "docker-f635a58e3ec4f5ff87cdd7b16054f26776c0aba0d6db961c1f1bf3c12cf1fd46.scope" with properties [{Name:Description Value:"libcontainer container f635a58e3ec4f5ff87cdd7b16054f26776c0aba0d6db961c1f1bf3c12cf1fd46"} {Name:Slice Value:"user.slice"} {Name:PIDs Value:@au [5181]} {Name:Delegate Value:true} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]: read unix @->/run/systemd/private: read: connection reset by peer: unknown.
ERRO[0000] error waiting for container: context canceled 
```

😞

**Comment by jandubois** [comment]
Just out of curiosity, why is `dbus-user-session` required? Doesn't `loginctl enable-linger` already do everything needed to keep the daemon running?

**Comment by AkihiroSuda** [comment]
Because runc needs to connect to dbus

https://github.com/moby/moby/issues/42793
https://github.com/opencontainers/runc/pull/3186

**Comment by jandubois** [comment]
> Because runc needs to connect to dbus

So why does it work for me even without `dbus-user-session` with just #369:

```
$ limactl start --tty=false examples/docker.yaml
[...]
$ DOCKER_HOST=unix://$HOME/docker.sock docker run -it --rm alpine uname -a
Linux 9d6f08041b9f 5.13.0-14-generic #14-Ubuntu SMP Mon Aug 2 12:43:35 UTC 2021 x86_64 Linux
```

**Comment by jandubois** [comment]
> So why does it work for me even without `dbus-user-session` with just #369:

Looks like it is installed already:

```console
root@lima-docker:~# apt -qq list dbus-user-session
dbus-user-session/impish 1.12.20-2ubuntu2 amd64
root@lima-docker:~# apt install aptitude
[...]
root@lima-docker:~# aptitude why dbus-user-session
i   ubuntu-server Depends  dirmngr
i A dirmngr       Suggests dbus-user-session
```

**Comment by AkihiroSuda** [comment]
`dbus-user-session` wasn't installed in http://cloud-images.ubuntu.com/impish/20211014/impish-server-cloudimg-amd64.img (sha256:fce2af66787ccfed5eef0de2ac38eaedacdd3d8ee8a645c26d5a736559265478) when `containerd.user` is set to `false`.

Maybe your cache revision is different.

**Comment by jandubois** [comment]
> Maybe your cache revision is different.

It is:

```console
$ ag -G url impish
download/by-url-sha256/ac74da77a6828e35de7edaa06fdbb33d12ef97cce2726550017e3c1066c88fb1/url
1:https://cloud-images.ubuntu.com/impish/current/impish-server-cloudimg-amd64.img
```

Still weird that the installed packages are changing, but I think there is little value in digging any deeper....

**Comment by jandubois** [comment]
Even weirder that my cached version seems older, but has a package that your version seems to be missing:

```console
$ ls -l ~/Library/Caches/lima/download/by-url-sha256/ac74da77a6828e35de7edaa06fdbb33d12ef97cce2726550017e3c1066c88fb1
total 1105208
-rw-r--r--  1 jan  staff  565051392  7 Sep 17:09 data
-rw-r--r--  1 jan  staff         79  7 Sep 17:08 url
```

Not sure how to determine the original download URL; I guess we don't store the endpoint of a redirect chain.

**Pull request merged**
