### PR TITLE
CI: add vz

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
```
[vz](https://github.com/lima-vm/lima/actions/runs/4799814791/jobs/8541941830?pr=1511#logs)
cancelled 33 minutes ago in 25m 56s
```

macos-13 infra seems still unstable

**Comment by AkihiroSuda** [comment]
- https://github.com/actions/runner-images/issues/7509

**Comment by balajiv113** [comment]
@AkihiroSuda - Looks like failure is related to number of cpus being 4 by default. The macos-13 runner has 3 cores and looks like its not able to allocate required resources.

I tried with using 1 cpu and the vz flow was fully running
https://github.com/balajiv113/lima/actions/runs/5163763720/jobs/9302272793

**Comment by AkihiroSuda** [comment]
> https://github.com/balajiv113/lima/actions/runs/5163763720/jobs/9302272793

Thanks, let's change the default dynamically:
- https://github.com/lima-vm/lima/pull/1603

**Comment by balajiv113** [comment]
Even setting to 3 cores didn't work. 
Mostly now its related to the resource allocation from the runner only. Nothing much from our end.

**Review by balajiv113 — APPROVED** [review]

**Pull request merged**
