### PR TITLE
9p: use `fscache` by default for RO mounts

### LINKED ISSUE #786: 9p: change the default cache mode from `mmap` to `fscache` (for read-only mounts, at least)
##  9p + `mmap`

```console
suda@lima-9p:/Users/suda/gopath/src/github.com/lima-vm/lima$ time du -hs
32M     .

real    0m2.620s
user    0m0.000s
sys     0m0.460s
suda@lima-9p:/Users/suda/gopath/src/github.com/lima-vm/lima$ time du -hs
32M     .

real    0m2.766s
user    0m0.000s
sys     0m0.338s
suda@lima-9p:/Users/suda/gopath/src/github.com/lima-vm/lima$ time du -hs
32M     .

real    0m2.429s
user    0m0.348s
sys     0m0.000s
```

##  9p + `fscache`

```console
suda@lima-9p-fscache:/Users/suda/gopath/src/github.com/lima-vm/lima$ time du -hs
32M     .

real    0m1.681s
user    0m0.000s
sys     0m0.300s
suda@lima-9p-fscache:/Users/suda/gopath/src/github.com/lima-vm/lima$ time du -hs
32M     .

real    0m0.680s
user    0m0.000s
sys     0m0.204s
suda@lima-9p-fscache:/Users/suda/gopath/src/github.com/lima-vm/lima$ time du -hs
32M     .

real    0m0.520s
user    0m0.044s
sys     0m0.044s
```

## SSHFS

```console
suda@lima-default:/Users/suda/gopath/src/github.com/lima-vm/lima$ time du -s
33912   .

real    0m1.702s
user    0m0.019s
sys     0m0.497s
suda@lima-default:/Users/suda/gopath/src/github.com/lima-vm/lima$ time du -s
33912   .

real    0m0.705s
user    0m0.010s
sys     0m0.405s
suda@lima-default:/Users/suda/gopath/src/github.com/lima-vm/lima$ time du -s
33912   .

real    0m0.682s
user    0m0.010s
sys     0m0.398s
```

(Lima: 939f79b4bd7e1e391e416bf96b4e325fddbbdc98 / QEMU: 6.2.0_1 (Homebrew))

`fscache` is significantly faster, so I suggest changing the default from `mmap` to `fscache`, at least for read-only mounts.

Previous discussion: https://github.com/lima-vm/lima/pull/726#issuecomment-1069700084

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #786

### CODE REVIEW

**Comment by matejsp** [comment]
Shouldn't default be based on not having any writeable mounts?
As in: any writeable -> default mmap else fscache?

**Comment by jandubois** [comment]
> Shouldn't default be based on not having any writeable mounts?
> As in: any writeable -> default mmap else fscache?

I don't think the default for one mount should depend on the `writable` property of a different mount.

This is not a global setting, so it would make more sense (to me) to say: defaults to `fscache` for readonly mounts and `mmap` for writable ones.

**Comment by AkihiroSuda** [comment]
Updated PR to keep `mmap` as the default for RW mounts

**Comment by jandubois** [comment]
> This is not a global setting, so it would make more sense (to me) to say: defaults to `fscache` for readonly mounts and `mmap` for writable ones.

Already implemented before I can press the "Comment" button! 😂

**Comment by afbjorklund** [comment]
Sounds good to me, it is more complex than just keeping the upstream default (of "none") but performance could be worth it...

I guess the same already applied to the msize parameter, where the upstream default (8K on Mac ) causes runtime warnings.

**Review by jandubois — APPROVED** [review]
LGTM

**Comment by LionsAd** [comment]
@AkihiroSuda one thing to note:

fscache failed miserably for me when doing the dd test.

eG as it’s read only,

 dd if=largefile of=/dev/null bs=1M count=1000

that said I tested writing and it failed, so maybe reading is fine but wanted to note it anyway.

**Pull request merged**
