### PR TITLE
docs(README): mention nerdctl.lima shortcut

### LINKED ISSUE #552: mention nerdctl.lima in README
In the blog posts I've read about lima and nerdctl, I noticed that people are not aware of the feature in lima that they can use nerdctl. Lima shortcut instead of typing "lima nerdctl." So, I thought it'd be great to mention this tool in README.

> please feel free to assign it to me. I'm willing to work on it.

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

Fixes #552

### CODE REVIEW

**Comment by jandubois** [comment]
If you mention `nerdctl.lima`, then you should also mention that there will be a symlink called `nerdctl` pointing to `nerdctl.lima`. This is only created when there is no `nerdctl` entry in the directory already though.

**Comment by developer-guy** [comment]
Thank you @jandubois, I've updated the documentation according to your feedback; would you mind reviewing it again?

**Comment by developer-guy** [comment]
> > There will be a symlink called nerdctl pointing to nerdctl.lima.
> 
> This is created only via `make install`. Not included in Homebrew/MacPorts/nix packages.

Should I add this to the information?

**Comment by jandubois** [comment]
> This is created only via `make install`.
> Not included in Homebrew/MacPorts/nix packages.

Isn't this a bug in the packaging (or the `Makefile`)?

If `make binaries` would create the symlink, then at least `brew` would install it:

```ruby
  def install
    system "make", "VERSION=#{version}", "clean", "binaries"

    bin.install Dir["_output/bin/*"]
    share.install Dir["_output/share/*"]
```

Is there a reason why you wouldn't want to include the symlink?

**Comment by AkihiroSuda** [comment]
> Isn't this a bug in the packaging (or the Makefile)?

Not a bug. Including `nerdctl -> nerdctl.lima` symlink conflicts with native `nerdctl`, Rancher Desktop's `nerdctl`, and colima's `nerdctl`.
(We have lots of `nerdctl` ... 😅 )

**Comment by developer-guy** [comment]
> > > There will be a symlink called nerdctl pointing to nerdctl.lima.
> > 
> > 
> > This is created only via `make install`. Not included in Homebrew/MacPorts/nix packages.
> 
> Should I add this to the information?

So, what do you say then? Do we need to mention that as additional info?

**Comment by AkihiroSuda** [comment]
> So, what do you say then? Do we need to mention that as additional info?

Yes, that would be appreciated.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
